added the option to load an empty config DB through an environment va…
B3Partners/tailormap-viewer pull request #196
Opened 2022-10-17 18:56 UTC by mvdstruijk

…riable

2022-10-18 08:00 UTC, mprins requested changes
- Where is the reference to the story in Jira? please create as part of https://b3partners.atlassian.net/browse/HTM-10
- Why are the added group descriptions only available in Dutch?

2022-10-20 09:04 UTC, matthijsln requested changes
Add documentation in README

2022-10-20 09:12 UTC, matthijsln approved these changes

2022-10-20 09:14 UTC, matthijsln commented on docker/db/docker-entrypoint-initdb.d/3-initialize-empty-database.sql.script
> +insert into category (id,name) values(0,'Categoriën');
We can think about solving this but not necessarily in this PR, the preloaded dump is not localized anyway. The user can just rename it.

2022-10-20 09:18 UTC, mprins commented on docker/db/docker-entrypoint-initdb.d/3-initialize-empty-database.sql.script
> +insert into category (id,name) values(0,'Categoriën');
You could add 2 versions of the empty database 1 English, one Dutch that you can have the admin select using the/an env variable. eg. `CONFIG_DB_INIT_EMPTY_NL` and `CONFIG_DB_INIT_EMPTY_EN`
note it is also and more importantly the user group descriptions, not just `Categoriën`.

but I'm not sure it is worth the effort at this time as the rest of the admin GUI seems to always be in Dutch always

2022-10-24 09:08 UTC, mprins approved these changes

2022-10-24 09:08 UTC, merged